version: "3.5"

services:
  jekyll:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sws-jekyll:latest
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
        #command: bundle exec jekyll serve -H 0.0.0.0 -t

